// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ReentrancyGuard$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ReentrancyGuard";
  readonly sourceName: "src/ReentrancyGuard.sol";
  readonly abi: [{"inputs":[],"name":"ReentrancyGuardReentrantCall","type":"error"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/src/ReentrancyGuard.sol";
  readonly buildInfoId: "solc-0_8_24-0b724f6de738795327e329d48bf3483e54e0d3c8";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ReentrancyGuard"]: ReentrancyGuard$Type;
    ["src/ReentrancyGuard.sol:ReentrancyGuard"]: ReentrancyGuard$Type;
  }
}